image: maven:3.9-eclipse-temurin-17

default:
  tags:
    - local

stages:
  - build
  - test
  - package
  - deploy

cache:
  paths:
    - .m2/repository

build:
  stage: build
  script:
    - .\mvnw.cmd -s .mvn/settings.xml --batch-mode compile

test:
  stage: test
  script:
    - .\mvnw.cmd -s .mvn/settings.xml --batch-mode test

package:
  stage: package
  script:
    - .\mvnw.cmd -s .mvn/settings.xml --batch-mode package
  artifacts:
    paths:
      - target/*.jar

deploy:
  stage: deploy
  variables:
    REVISION: "$BASE_VERSION.$CI_PIPELINE_IID"
  script:
    # 1. Afficher la version
    - echo "Version maven utilisée : $REVISION"
    # 2. Exécuter le déploiement avec le profil de déploiement (si nécessaire) et la bonne version
    - mvn -s .mvn/settings.xml --batch-mode clean deploy
  only:
    - master
